import { describe, it, expect } from 'vitest'
import { emitScript } from './scriptEmitter'
import { codeReviewLoop } from '@/spec/seed'
import type { WorkflowSpec } from '@/spec/schema'

describe('emitScript — runtime-faithful contract', () => {
  it('emits a meta block with the workflow name and one phase per step', () => {
    const out = emitScript(codeReviewLoop)
    expect(out).toContain('export const meta = {')
    expect(out).toContain('name: "code-review-loop"')
    expect(out).toContain('{ title: "Phase 1", detail: "step — reviewer → claude-opus-4-8" }')
  })

  it('routes each stage to its resolved model via agent({ model })', () => {
    const out = emitScript(codeReviewLoop)
    expect(out).toContain('model: "claude-opus-4-8"')
    expect(out).toContain('model: "claude-sonnet-4-6"')
    expect(out).toContain('model: "claude-haiku-4-5"')
  })

  it('resolves aliases and omits model for inherit (== session model)', () => {
    const spec: WorkflowSpec = {
      ...codeReviewLoop,
      agents: [
        { id: 'a', name: 'a', model: 'opus', prompt: 'do a' },
        { id: 'b', name: 'b', model: 'inherit', prompt: 'do b' },
      ],
      root: { type: 'sequence', steps: [{ type: 'agent', agent: 'a' }, { type: 'agent', agent: 'b' }] },
    }
    const out = emitScript(spec)
    expect(out).toContain('model: "claude-opus-4-8"') // alias resolved
    // inherit agent carries a label but no model key
    expect(out).toContain('{ label: "b" }')
  })

  it('caps fan-out item count in-script (a real bound, not just concurrency)', () => {
    const out = emitScript(codeReviewLoop)
    expect(out).toContain('.slice(0, 8)')
    expect(out).toContain('await parallel(')
  })

  it('fails loud on a dangling ref rather than emitting a silently-broken stage', () => {
    const spec: WorkflowSpec = {
      ...codeReviewLoop,
      root: { type: 'sequence', steps: [{ type: 'fanout', agent: 'ghost', cap: 4 }] },
    }
    expect(emitScript(spec)).toContain('throw new Error("Unresolved agent ref \\"ghost\\"')
  })

  it('is deterministic (same spec → identical output)', () => {
    expect(emitScript(codeReviewLoop)).toBe(emitScript(codeReviewLoop))
  })

  it('matches the golden script for the code-review-loop seed', () => {
    expect(emitScript(codeReviewLoop)).toMatchInlineSnapshot(`
      "// Dynamic workflow — generated by Dynamic Workflow Editor (one-way export; edit the spec, not this file).
      // Target: claude-code dynamic-workflow runtime · probed 2026-07-02
      // Caps — concurrency 8, total 1000 (fan-out counts are capped in-script; concurrency is the runtime's global cap).

      export const meta = {
        name: "code-review-loop",
        description: "code-review-loop",
        phases: [
          { title: "Phase 1", detail: "step — reviewer → claude-opus-4-8" },
          { title: "Phase 2", detail: "fan-out — investigator → claude-sonnet-4-6 (dynamic-N, cap 8)" },
          { title: "Phase 3", detail: "step — synthesizer → claude-haiku-4-5" },
        ],
      }

      // --- generated helpers ---
      // Coerce a prior phase result into a list of items to fan out over. Best-effort:
      // arrays pass through; {items|findings} arrays are unwrapped; a string is split on blank
      // lines / list markers, falling back to single newlines. This is a HEURISTIC — for a
      // strict N, give the producing agent an output schema so it returns a real array.
      function toItems(x) {
        if (Array.isArray(x)) return x
        if (x && Array.isArray(x.items)) return x.items
        if (x && Array.isArray(x.findings)) return x.findings
        if (x == null) return []
        const s = String(x).trim()
        let parts = s.split(/\\n{2,}|\\n(?=\\s*[-*\\d])/).map((p) => p.trim()).filter(Boolean)
        if (parts.length <= 1) parts = s.split(/\\n+/).map((p) => p.trim()).filter(Boolean)
        return parts
      }
      function asText(x) {
        return typeof x === "string" ? x : JSON.stringify(x, null, 2)
      }

      phase("Phase 1")
      const p1 = await agent(
        "Review the diff on the current branch for correctness bugs and security issues. Group findings by severity and output one finding per item.",
        { model: "claude-opus-4-8", label: "reviewer" },
      )

      phase("Phase 2")
      const p2 = (await parallel(
        toItems(p1).slice(0, 8).map((item) => () =>
          agent(
            "Given a single finding, reproduce it, trace the root cause, and propose the minimal fix." + "\\n\\nInput:\\n" + asText(item),
            { model: "claude-sonnet-4-6", label: "investigator" },
          ),
        ),
      )).filter(Boolean)

      phase("Phase 3")
      const p3 = await agent(
        "Merge all investigation reports into one ranked review summary with clear next actions." + "\\n\\nInput from the previous phase:\\n" + asText(p2),
        { model: "claude-haiku-4-5", label: "synthesizer" },
      )

      return p3"
    `)
  })
})
